# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "devops"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Defined IP address using NAT.
  config.vm.network :hostonly, "10.11.12.13"
  # config.vm.network :bridged

  # Ensures that apt-get is updated before settings puppet
  # Was necessary to make this change to display the DNS Puppet
  config.vm.provision :shell, :inline =>
    "if [[ ! -f /apt-get-run ]]; then sudo apt-get update && sudo touch /apt-get-run && apt-get -y install python-software-properties && mkdir -p /root/.ssh && chmod 0700 /root/.ssh; fi"

  config.vm.share_folder ".ssh", "/home/vagrant/.ssh", "~/.ssh"

  # Defining settings puppet
  config.vm.provision :puppet do |puppet|
    # Folder location of Manifests
    puppet.manifests_path = "manifests"

    # Manifest file that you want to be called early
    puppet.manifest_file  = "devops.pp"

    # Folder where the module is located in the puppet
    puppet.module_path = "./modules"

    puppet.options = "--verbose"
  end
end
